services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tododb
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./todo-backend
    container_name: todo-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret

  frontend:
    build:
      context: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
